#!/bin/bash

./ASGA
read -rsn1 -p"Ready? - press any key to continue";echo;echo

./ASGB
read -rsn1 -p"Ready? - press any key to continue";echo;echo

./ASGC
read -rsn1 -p"Ready? - press any key to continue";echo;echo